### ISSUE TITLE
It doesn't works when page already has an anchor-tag

### ISSUE THREAD

**Issue by miaowm5** [ameesme/SlimScroller.js#1]
This lib is simple and amazing.But when I use SlimScroller Base version, I found it doesn't works when  url already has an anchor-tag.

...OK, I'm not use English and my English is poor...
What I mean is
When user type https://github.com on browser and click #hello to visit https://github.com#hello, it works well. But when user type https://github.com#world on browser  and click #hello to visit https://github.com#hello,it doesn't works...

**Comment by ameesme** [comment]
Ouch! I will look into that. Thanks for the feedback!

**Comment by ameesme** [comment]
This was caused by the function that binds click-events to anchor-tags. [This comparison](https://github.com/ameesme/SlimScroller.js/blob/master/src/slimScroller.full.js#L67) caused it not to fire.

Fixing it right away! Thanks a lot for the heads up!
